name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: build_directory
      run: mkdir build
    - name: going to build directory
      run: cd build
    - name: Generating project with cmake
      run: cmake ..
    - name: Building project
      run: make all
    - name: testing app
      run: cd test && ./test
