name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Generating project with cmake
      run: cmake .
    - name: Building project
      run: make all
    - name: going to test folder
      run: cd test
    - name: Checking if we are in test folder or not
      run: pwd
    - name: run app
      run: ./test
