name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Generating project with cmake
      run: cmake .
    - name: Building project
      run: make all
    - name: check all directory files and folder
      run: ls
    - name: run test
      run: "./test/test"
